dist: trusty
sudo: required
#cache: true

# Blacklist
branches:
  except:
    - gh-pages

language: csharp
solution: YarnSpinner.sln

# Environment variables

env:
  global:
    - DOXYFILES_ROOT: $TRAVIS_BUILD_DIR/Documentation
    - GH_REPO_NAME: YarnSpinner
    - GH_REPO_USER: TheSecretLab
    - WANTED_DOCS: '"html latex rtf xml"'
    - VERBOSE: false
    - secure: "SW26GHKfixdYsbZ1yCHe5qI2OekA7Y+FbUBf9oSY/JOB/wfVw7mCH0sJ2Y5gYte3NywnCeNkRRvuW3JkCk1g0i3rjyvB5FP3CwHmEdIzgs9UIprNuaIXUF8/sKL3UZyElIWRTe/na2bLRYJ2C09pXzS0armUULn3FohSxegQwPFpisDzWPC+CAfaNwTHUnFAZ66fPwbqLIRScMvgK0ie8nni3VI6kokkb4SE3QL5EewguoZq9WCeWv+x0u1l3v8rUVmL0OjBZLloILjKwi8liRoqO9GHd8BQYaRbRwWkoLW4RJ4Hq0MephkYUzX/FOzTZpRM8dugM23yXkw8iYiqYZQDuCTBh9Zn11h8SDA3SGAK2dS4alM9haHVr6b5Y74xaa/n7G+8QWevUz0MQ83LkYeLvLWod9yzxGkMgg5ggtdOTQlFPebn5KeO88aDPu08US0hJiYxiXIbo/DY25aArQ5/wvhExNd4rWesbd6NWUi5M7hWH3WiNiiE7+ktvzktqikao0w6zdZyNlFCx61Q2uUTybpjJ5DlTF9On53RBuEiF9Yqo8eEm4m1mtIATc6io9ez78ub+ak/atsI//h55RdVaKnIPxDq5H/za9UhV+j0uRSGfXCVEL0Zf57X0KNYSlESByvZEUmWrJOQqalZFzXuOhtCr7te9/8JXThUU94="

# Install dependencies
addons:
  apt:
    packages:
      - global
#      When using doxygen
      - libjs-jquery
      - graphviz
#      When using supplied doxygen
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui

install:
  - nuget restore YarnSpinner.sln

script:	
  - ./build.sh -bcdv

# deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x DeployDocumentation.sh
  - ./DeployDocumentation.sh
