name: Create Release

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Get release notes preface
        id: release_preface
        run: echo ::set-output name=contents::$(cat .github/RELEASE_TEMPLATE.md)
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: true
          body: |
            ${{ steps.release_preface.outputs.contents }}
            ${{ steps.extract-release-notes.outputs.release_notes }}

 
